export const FICTIONAL_CITY_POOL = [
  "Harbor City",
  "Cascadia",
  "Northstar",
  "Prairie",
  "Iron Valley",
  "Metro",
  "Summit",
  "Atlantic",
  "Lakeside",
  "Bayview",
  "Capital",
  "Desert",
  "Frostholm",
  "Bridgeport",
  "Silverpine",
  "Red Mesa",
  "Port Azure",
  "Cedar Falls",
  "Glacier Bend",
  "Elm Harbor",
  "Copper Ridge",
  "Stonebridge",
  "Aurora Bay",
  "Rivergate",
  "Pinehaven",
  "Quartz Coast"
];
